### ISSUE TITLE
Netlabs rel metadata is broken

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/rpm-issues#34] opened 2024-08-05 22:26 UTC
Attempting to refresh the current metadata returns:

[Errno 2] No such file or directory: '/@unixroot/var/cache/yum/netlabs-rel/959a5
065a99df5b5b4d7e8672bbf1b90a4c9135f653d52968d19b4ae0dba9085-primary.sqlite.bz2' 

This also breaks the 2rosenthals.com mirror.

I can confirm, however, that building the metadata locally from the mirrored repository files with:

createrepo_c --unique-md-filenames -d .

generates usable metadata (though with a few errors during the createrepo_c pass - hopefully, these are cosmetic only, but I have not verified that, yet).

I'm not sure what broke in the Netlabs metadata update process or when. I do know that it has not corrected itself in the past few days.

**Comment by SilvanScherrer** [comment] 2024-08-06 05:31
this is not a rpm issue. The problem is on the netlabs server. Adrian is aware of it and searches for a solution. so closing it

**Closed as completed by SilvanScherrer** 2024-08-06 05:31 UTC

**Comment by SilvanScherrer** [comment] 2024-08-06 06:50
comment from netlabs web:

netlabs.org Website
As you will have encountered, there are some issues with the various netlabs-services. They are being investigated and some are back, like wiki and blog, but might drop out again.
